import React from 'react'
import './Left.css'
import HVideo from '../../Explore/explore/HVideo/HVideo'

function Left() {
    return (
        <div className='left'>
            <h5 style={{marginLeft:"58px"}}>Watch History</h5>
            <p className='when'>Today</p>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <p  className='when'>Yesterday</p>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <p className='when'>Thursday</p>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <p className='when'>Wednesday</p>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
            <HVideo image='https://i.ytimg.com/vi/5R9jFHlG6ik/maxresdefault.jpg' title='SideBar Menu Tutorial React JS - Beginner Navigation Tutorial' channel='PedroTech' views='63K views' description='In this video I will show you guys how to make a responsive Sidebar In React Js. I showed you guys how I do this in an old video, but I...'/>
        </div>
    )
}

export default Left